### PR TITLE
[#100] Fix incorrect method delegation

### LINKED ISSUE #100: Some methods are not being correctly delegated
To reproduce:

```ruby
require 'surrealist'

class Foo
  def test
    'test'
  end
end

class FooSerializer < Surrealist::Serializer
  json_schema { { test: String } }
end

FooSerializer.new(Foo.new).build_schema

# => ArgumentError (wrong number of arguments (given 0, expected 2..3))
```

The method Surrealist is calling is `Kernel#test`, while it should have called `Foo.new.test`.

The bug was introduced by commit 9f89b2d6ba69f6a9678670b5f659e84d68034849.

### PR DESCRIPTION
**Pull request by nesaulov**
Fixes #100

### CODE REVIEW

File: lib/surrealist/value_assigner.rb [hunk 1]
```diff
@@ -34,10 +34,23 @@ def assign(schema, instance)
...
       end
 
+      # Checks if there is a custom serializer defined for the object and invokes the method
+      #   on it first.
+      #
+      # @param [Object] instance an instance of a model or a serializer
+      # @param [Symbol] method the schema key that represents the method to be invoked
+      #
+      # @return [Object] the return value of the method
+      def invoke_method(instance, method)
```
Comment (AlessandroMinali) [inline lib/surrealist/value_assigner.rb]: Looks good but would this make more sense being inside the `Serializer` class?

Comment (nesaulov) [reply lib/surrealist/value_assigner.rb]: I guess it would, but it's quite complicated to move this method there - it would result in a massive code duplication.

Comment (AlessandroMinali) [reply lib/surrealist/value_assigner.rb]: Fooling around a bit with the code I see what you mean.
