### PR TITLE
[Fix] Conflict when root and object property share the same name

### LINKED ISSUE #95: Conflict when root and and object property share the same name
There seems to be a problem with serializing an object with a root that is the same as one of it's properties.

```rb
Foo = Struct.new(:foo, :bar)
Foo.include Surrealist
Foo.json_schema { { bar: String } }

foo = Foo.new('foo', 'bar')

foo.surrealize
# => "{\"bar\":\"bar\"}"

foo.surrealize(include_root: true)
# Surrealist::UndefinedMethodError: undefined method `bar' for "foo":String. You have probably defined a key in the schema that doesn't have a corresponding method.

foo.surrealize(root: 'foo')
# Surrealist::UndefinedMethodError: undefined method `bar' for "foo":String. You have probably defined a key in the schema that doesn't have a corresponding method.

foo.surrealize(root: 'fooz')
# => "{\"fooz\":{\"bar\":\"bar\"}}"
```

### PR DESCRIPTION
**Pull request by akxcv**
Fixes #95.

**Why does it fail?**

First, we normalize the schema, which includes wrapping it in a root, if given. (This also happens with namespaces.)

Then, the normalized schema is passed to the Builder along with the instance (from the example given in #95, we get something like `instance: #<Foo:0x00007fb2651a1db8>, schema: { foo: { foo: String, bar: String } }`

Afterward, the Builder iterates through the schema's key-value pairs. When `instance.respond_to?(:foo)`, the Builder calls itself again, this time with `instance.foo` as the instance and `{ foo: String, bar: String }` as the schema. You should see the problem now.

**My proposed fix**

I found that the builder only needs to know the actual schema, without any roots or namespaces. So, the current algorithm of serialization is `copy -> build -> wrap` instead of `copy&wrap -> build`.

I've split `Copier` into `Copier` and `Wrapper`, which should make their respective responsibilities clearer.

P.S I couldn't come up with any good real-world examples of this use-case for the specs 😞

### CODE REVIEW

File: lib/surrealist.rb [hunk 1]
```diff
@@ -129,17 +130,18 @@ def build_schema(instance:, **args)
 
       parameters = config ? config.merge(args) : args
       carrier = Surrealist::Carrier.call(parameters)
-      normalized_schema = Surrealist::Copier.deep_copy(schema, carrier, instance.class.name)
-      hash = Builder.new(carrier, normalized_schema, instance).call
-      carrier.camelize ? Surrealist::HashUtils.camelize_hash(hash) : hash
+      copied_schema = Surrealist::Copier.deep_copy(schema)
+      built_schema = Builder.new(carrier, copied_schema, instance).call
+      wrapped_schema = Surrealist::Wrapper.wrap(built_schema, carrier, instance.class.name)
```
Comment (akxcv) [inline lib/surrealist.rb]: This code makes me a little anxious, maybe we should encapsulate this via something like a command pattern here?

File: lib/surrealist/hash_utils.rb [hunk 2]
```diff
@@ -3,6 +3,8 @@
 module Surrealist
   # A helper class for hashes transformations.
   module HashUtils
+    EMPTY_HASH = {}.freeze
```
Comment (akxcv) [inline lib/surrealist/hash_utils.rb]: `HashUtils` seems like a more obvious place to store this.

**Comment by nesaulov** [comment]
@akxcv thank you for the PR and such a detailed explanation! I am vacationing right now, so I'll review this next week

File: lib/surrealist.rb (hunk 1 above)
Comment (nesaulov) [reply lib/surrealist.rb]: Yes, you are right, and it would be very nice of you to refactor this part a bit.

File: lib/surrealist/hash_utils.rb (hunk 2 above)
Comment (nesaulov) [reply lib/surrealist/hash_utils.rb]: Yep

File: lib/surrealist/wrapper.rb [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+
+      # Deeply copies the schema hash and wraps it if there is a need to.
+      #
+      # @param [Object] hash object to be copied.
+      # @param [String] klass instance's class name.
+      # @param [Object] carrier instance of Carrier class that carries arguments passed to +surrealize+
+      # @param [Bool] namespaces_condition whether to wrap into namespace.
+      #
+      # @return [Hash] deeply copied hash, possibly wrapped.
+      def possibly_wrapped_hash(hash, klass, carrier, namespaces_condition)
```
Comment (nesaulov) [inline lib/surrealist/wrapper.rb]: Well, this also doesn't look good in fact. Could you please leave a TODO note to refactor this later?

File: spec/include_namespaces_spec.rb [hunk 4]
```diff
@@ -288,5 +315,48 @@ def withdraws_amount
...
+
+      let(:snake_hash) do
+        {
+          evil_events: {
+            core: {
+              metadata: { core: true, author: '0exp' },
+            },
+          },
+        }
+      end
```
Comment (nesaulov) [inline spec/include_namespaces_spec.rb]: Could you please add spaces between `let`s?

**Comment by nesaulov** [comment]
hey @akxcv, any updates on this?

**Comment by akxcv** [comment]
Added a TODO comment. Let's release the fix already :)
